import type {
  ApiErrorPayload,
  BackgroundImageFillMode,
  HealthResponse,
  KnowledgeLibraryResponse,
  KnowledgeNote as ContractsKnowledgeNote,
  KnowledgeNoteCreateRequest,
  KnowledgeNoteUpdateRequest,
  LLMConfigResponse,
  LocalModelsMigrationResponse,
  ModelComponentType,
  ModelDescriptor,
  ModelDownloadState,
  ModelDownloadStatus,
  ModelListResponse,
  ModelRuntimeStatus,
  OllamaModelsMigrationResponse,
  OllamaRuntimeConfigResponse,
  OllamaServiceStatusResponse,
  PromptTemplateBundleResponse,
  PromptTemplateChannel,
  PromptTemplateItem,
  RuntimeMetricsResponse,
  RuntimePathsResponse,
  SelfCheckIssueResponse,
  SelfCheckReportResponse,
  SelfCheckStartResponse,
  SelfCheckStepResponse,
  SelfCheckStreamEvent,
  SourceType,
  TaskBatchCreateResponse,
  TaskCreateFromPathRequest,
  TaskCreateFromUrlRequest,
  TaskCreateResponse,
  TaskDetailResponse as ContractsTaskDetailResponse,
  TaskExportKind,
  TaskListResponse,
  TaskRecentItem as ContractsTaskRecentItem,
  TaskRecentResponse,
  TaskArtifactsUpdateRequest,
  TaskStatsResponse,
  TaskStatus,
  TaskStreamEvent,
  TaskSummaryItem as ContractsTaskSummaryItem,
  TaskTitleUpdateRequest,
  TaskStepItem,
  TaskStepStatus,
  TaskSourceCreatePayload,
  TranscriptSegment,
  StudyPreview,
  StudyState,
  StudyWorkbenchResponse,
  UISettingsResponse,
  VqaChatStreamEvent,
  VqaCitationImageEvidence,
  VqaCitationItem,
  VqaTraceRecord,
  VqaTraceResponse,
  WhisperConfigResponse,
  WhisperRuntimeLibrariesInstallState,
  WhisperRuntimeLibrariesProgressResponse,
  WhisperRuntimeLibrariesResponse,
  WhisperRuntimeLibrariesStatus,
  WorkflowType,
} from "@vidgnost/contracts"

export type {
  ApiErrorPayload,
  BackgroundImageFillMode,
  HealthResponse,
  LLMConfigResponse,
  LocalModelsMigrationResponse,
  ModelComponentType,
  ModelDescriptor,
  ModelDownloadState,
  ModelDownloadStatus,
  ModelListResponse,
  ModelRuntimeStatus,
  OllamaModelsMigrationResponse,
  OllamaRuntimeConfigResponse,
  OllamaServiceStatusResponse,
  PromptTemplateBundleResponse,
  PromptTemplateChannel,
  PromptTemplateItem,
  RuntimeMetricsResponse,
  RuntimePathsResponse,
  SelfCheckIssueResponse,
  SelfCheckReportResponse,
  SelfCheckStartResponse,
  SelfCheckStepResponse,
  SelfCheckStreamEvent,
  SourceType,
  TaskBatchCreateResponse,
  TaskCreateResponse,
  TaskExportKind,
  TaskListResponse,
  TaskRecentResponse,
  TaskArtifactsUpdateRequest,
  TaskStatsResponse,
  TaskStatus,
  TaskStreamEvent,
  TaskTitleUpdateRequest,
  TaskStepItem,
  TaskStepStatus,
  TaskCreateFromPathRequest,
  TaskCreateFromUrlRequest,
  TaskSourceCreatePayload,
  TranscriptSegment,
  StudyPreview,
  StudyState,
  StudyWorkbenchResponse,
  UISettingsResponse,
  VqaChatStreamEvent,
  VqaCitationImageEvidence,
  VqaCitationItem,
  VqaTraceRecord,
  VqaTraceResponse,
  WhisperConfigResponse,
  WhisperRuntimeLibrariesInstallState,
  WhisperRuntimeLibrariesProgressResponse,
  WhisperRuntimeLibrariesResponse,
  WhisperRuntimeLibrariesStatus,
  WorkflowType,
  KnowledgeLibraryResponse,
  KnowledgeNoteCreateRequest,
  KnowledgeNoteUpdateRequest,
}

export type StudyPackResponse = StudyWorkbenchResponse
export type StudyStateResponse = StudyState & {
  last_selected_subtitle_track_id?: string | null
}
export type StudyStateUpdateRequest = Partial<StudyStateResponse> & {
  playback_position_seconds?: number | null
  last_selected_subtitle_track_id?: string | null
}
export type KnowledgeNoteItem = ContractsKnowledgeNote
export type KnowledgeNoteListResponse = KnowledgeLibraryResponse

export type TaskSummaryItem = ContractsTaskSummaryItem & {
  study_preview?: Partial<StudyPreview> | null
}

export type TaskRecentItem = ContractsTaskRecentItem & {
  study_preview?: Partial<StudyPreview> | null
}

export type TaskDetailResponse = ContractsTaskDetailResponse & {
  study_preview?: Partial<StudyPreview> | null
}
